### ISSUE TITLE
config-options.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [Rostomjan/shop#3]
Почему-то нет методов извлечения данных.

**Comment by Rostomjan** [comment]
Не совсем понял, что имеется в виду под извлечением. Не получении всех свойств, а каждое по отдельности??

**Comment by VZhyrytskiy** [comment]
Сорри, это не ваше ишью. Случайно несколько ишью полетели не туда. У вас все ок.

**Comment by Rostomjan** [comment]
Ok, понял. Спасибо
