### ISSUE TITLE
products.actions.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [Rostomjan/shop#7]
А зачем это понадобилось?
declare module '@ngrx/store' {
  interface Action {
    type: string;
    payload?: any;
  }
}

**Comment by Rostomjan** [comment]
У меня WebStorm на payload ругался (подсвечивал и при билде иногда тоже выдавал ошибки) - не мог свойство это найти (Unresolved variable payload). Поэтому перезаписал интерфейс, хотя в принципе можно было кастомный создать

**Comment by VZhyrytskiy** [comment]
Ясно.
